=== tungri/dcm4chee/dcm4jboss-ejb/src/etc/common/conf/dcm4chee-attribute-filter.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
This is the XML DTD for the dcm4chee attribute filter descriptor.

Minimal descriptor for DICOM Standard Conformance of Query/Retrieve Service:
  <dcm4chee-attribute-filter>
    <soundex class="org.dcm4che2.soundex.Soundex" trailingWildCard="false"/>
    <patient>
        <attr tag="00080005"/>
        <attr tag="00100010" case-sensitive="false"/>
        <attr tag="00100020"/>
    </patient>
    <exclude-patient exclude="true" tsuid="1.2.840.10008.1.2.1.99">
        <attr tag="00081120"/>
        <attr tag="00100010"/>
        <attr tag="00100020"/>
    </exclude-patient>
    <study>
        <attr tag="00080005"/>
        <attr tag="00080020"/>
        <attr tag="00080030"/>
        <attr tag="00080050"/>
        <attr tag="0020000D" coerce="false"/>
        <attr tag="00200010"/>
    </study>
    <series>
        <attr tag="00080060"/>
        <attr tag="0020000E" coerce="false"/>
        <attr tag="00200011"/>
    </series>
    <instance>
        <attr tag="00080016"/>
        <attr tag="00080018"/>
        <attr tag="00200013"/>
    </instance>
  </dcm4chee-attribute-filter>
-->

<!ELEMENT dcm4chee-attribute-filter (soundex?,patient,exclude-patient,study,series,instance+)>

<!ELEMENT soundex EMPTY>
<!ATTLIST soundex class CDATA #REQUIRED>
<!ATTLIST soundex trailing-wildcard (true | false) "true">

<!ELEMENT patient (attr)*>
<!ATTLIST patient tsuid CDATA #IMPLIED>
<!ATTLIST patient exclude (false) "false">
<!ATTLIST patient exclude-private (false) "false">
<!ATTLIST patient update-strategy (coerce-merge) "coerce-merge">

<!ELEMENT exclude-patient (attr)*>
<!ATTLIST exclude-patient tsuid CDATA #IMPLIED>
<!ATTLIST exclude-patient exclude (true) "true">
<!ATTLIST exclude-patient exclude-private (false) "false">
<!ATTLIST exclude-patient update-strategy (coerce-merge) "coerce-merge">

<!ELEMENT study (attr)*>
<!ATTLIST study tsuid CDATA #IMPLIED>
<!ATTLIST study exclude (false) "false">
<!ATTLIST study exclude-private (false) "false">
<!ATTLIST study update-strategy (overwrite | overwrite-merge |
                                 coerce | coerce-merge) "coerce-merge">

<!ELEMENT series (attr)*>
<!ATTLIST series tsuid CDATA #IMPLIED>
<!ATTLIST series exclude ( false ) "false">
<!ATTLIST series exclude-private ( false ) "false">
<!ATTLIST series update-strategy (overwrite | overwrite-merge |
                                  coerce | coerce-merge) "coerce-merge">

<!ELEMENT instance (attr)*>
<!ATTLIST instance cuid CDATA #IMPLIED>
<!ATTLIST instance tsuid CDATA #IMPLIED>
<!ATTLIST instance exclude (true | false ) "false">
<!ATTLIST instance exclude-private (true | false ) "false">
<!ATTLIST instance update-strategy (overwrite | overwrite-merge |
                                    coerce | coerce-merge) "overwrite">
<!ATTLIST instance content-item-text-value-max-length CDATA "250">

<!ELEMENT attr EMPTY>
<!ATTLIST attr tag CDATA #IMPLIED>
<!ATTLIST attr seq CDATA #IMPLIED>
<!ATTLIST attr vr (AE | AS | AT | CS | DA | DS | DT | FL |
                   FD | IS | LO | LT | OB | OF | OW | PN |
                   SH | SL | SQ | SS | ST | TM | UI | UL |
                   UN | US | UT) #IMPLIED>
<!ATTLIST attr coerce (true | false ) "true">
<!ATTLIST attr case-sensitive (true | false ) "true">

=== tungri/dcm4chee/dcm4jboss-ejb/src/etc/common/conf/dcm4chee-minimal-attribute-filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dcm4chee-attribute-filter SYSTEM "dcm4chee-attribute-filter.dtd">
<dcm4chee-attribute-filter>
    <soundex class="org.dcm4che2.soundex.Soundex" trailing-wildcard="false"/>
    <!--
    <soundex class="org.dcm4che2.soundex.ESoundex"/>
    <soundex class="org.dcm4che2.soundex.ESoundex2"/>
    <soundex class="org.dcm4che2.soundex.KPhonetik"/>
    <soundex class="org.dcm4che2.soundex.Metaphone"/>
    <soundex class="org.dcm4che2.soundex.Phonem"/>
    -->
    <patient>
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00100010" case-sensitive="false"/> <!--  Patient's Name -->
        <attr tag="00100020"/> <!--  Patient ID -->
    </patient>
    <exclude-patient exclude="true" tsuid="1.2.840.10008.1.2.1.99">
        <attr tag="00081120"/> <!-- Referenced Patient Sequence -->
        <attr tag="00100010"/> <!--  Patient's Name -->
        <attr tag="00100020"/> <!--  Patient ID -->
    </exclude-patient>
    <study>
        <attr tag="00080005"/> <!-- Specific Character Set -->
        <attr tag="00080020"/> <!-- Study Date -->
        <attr tag="00080030"/> <!-- Study Time -->
        <attr tag="00080050"/> <!-- Accession Number -->
        <attr tag="0020000D" coerce="false"/> <!-- Study Instance UID -->
        <attr tag="00200010"/> <!-- Study ID -->
    </study>
    <series>
        <attr tag="00080060"/> <!-- Modality -->
        <attr tag="0020000E" coerce="false"/> <!-- Series Instance UID -->
        <attr tag="00200011"/> <!-- Series Number -->
    </series>
    <instance>
        <attr tag="00080016"/> <!-- SOP Class UID -->
        <attr tag="00080018"/> <!-- SOP Instance UID -->
        <attr tag="00200013"/> <!-- Instance Number -->
    </instance>
</dcm4chee-attribute-filter>
