=== tungri/dcm4chee/dcm4chee-docstore-store/src/main/resources/conf/dcm4chee-docstore/dcm4chee-docstore-cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="DocumentStoreCfg">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="StoreDomain"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StoreDomain">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Store"/>
      </xs:sequence>
      <xs:attribute name="desc" />
      <xs:attribute name="name" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="Store">
    <xs:complexType>
       <xs:sequence>
         <xs:element minOccurs="1" maxOccurs="1" name="init"/>
         <xs:element ref="FeatureList" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="desc" />
      <xs:attribute name="name" use="required" />
      <xs:attribute name="type" use="required" />
      <xs:attribute name="pool" />
    </xs:complexType>
  </xs:element>
  <xs:element name="FeatureList">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="Feature"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Feature">
    <xs:complexType>
      <xs:attribute name="name" use="required" />
      <xs:attribute name="desc" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== tungri/dcm4chee/dcm4chee-docstore-store/src/main/resources/conf/dcm4chee-docstore/dcm4chee-docstore-cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<DocumentStoreCfg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="dcm4chee-docstore-cfg.xsd">
    <StoreDomain name="RID" >
        <Store name="RIDStore" type="SimpleFileStorage" desc="File Storage for RID Domain" >
            <!--  SimpleFileStorage supports following init parameter:
                    BASE_DIR........Base directory default:store/docs
                    minFree.........Min free space in bytes (if freeSpace < minFree: UNAVAILABLE) default:10000000
                    checkIntervall..After this period of time in ms a new checkAvailability is forced. default:
                    dfCmdName.......Name of DFCommand Service which provide a platform independent freeSpace method. default:600000
                    disableHash.....If set no SHA1 hash calculation is performed. default: SHA1 is enabled.
            -->
    		<init>BASE_DIR=docstore/rid/store
            	  ;disableHash=true
    		</init>
            <FeatureList>
                <Feature name="CACHE"/>
                <Feature name="RID_RETRIEVE"/>
            </FeatureList>
        </Store>
    </StoreDomain>
    <StoreDomain name="XDS" >
        <Store name="XDSStore_1" type="SimpleFileStorage" desc="File Storage for XDS Domain" pool="uncommitted">
            <init>BASE_DIR=docstore/xds/uncommitted</init>
            <FeatureList>
                <Feature name="RID_RETRIEVE"/>
            </FeatureList>
        </Store>
        <Store name="XDSStore_2" type="SimpleFileStorage" desc="File Storage for XDS Domain" pool="committed">
            <init>BASE_DIR=docstore/xds/committed</init>
            <FeatureList>
                <Feature name="RID_RETRIEVE"/>
            </FeatureList>
        </Store>
        <Store name="XDSMetadata" type="SimpleFileStorage" desc="File Storage for XDS Metadata" pool="metadata" >
            <init>BASE_DIR=docstore/xds/metadata</init>
            <FeatureList>
                <Feature name="RID_RETRIEVE"/>
            </FeatureList>
        </Store>
    </StoreDomain>
 </DocumentStoreCfg>

=== tungri/dcm4chee/dcm4chee-docstore-store/target/test-classes/test_docstore_cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<DocumentStoreCfg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="dcm4chee-docstore-cfg.xsd">
    <StoreDomain name="TEST" >
        <Store name="TestStore" type="SimpleFileStorage" desc="TEST File Storage (Domain: TEST)" >
    		<init>BASE_DIR=target/docstore/test/store
            	  ;disableHash=true
    		</init>
            <FeatureList>
                <Feature name="cache"/>
                <Feature name="TEST_RETRIEVE"/>
            </FeatureList>
        </Store>
    </StoreDomain>
    <StoreDomain name="POOL" >
        <Store name="PoolStore_1_1" type="SimpleFileStorage" desc="File Storage (Domain POOL)" pool="pool1">
            <init>BASE_DIR=target/docstore/test/pool1_1
                  checkIntervall=-1    
            </init>
            <FeatureList>
                <Feature name="TEST_RETRIEVE"/>
            </FeatureList>
        </Store>
        <Store name="PoolStore_1_2" type="SimpleFileStorage" desc="File Storage (Domain POOL)" pool="pool1">
            <init>BASE_DIR=target/docstore/test/pool1_2
                  checkIntervall=-1    
            </init>
            <FeatureList>
                <Feature name="TEST_RETRIEVE"/>
            </FeatureList>
        </Store>
        <Store name="PoolStore_2_1" type="SimpleFileStorage" desc="File Storage (Domain POOL)" pool="pool2">
            <init>BASE_DIR=target/docstore/test/pool2_1
                  checkIntervall=-1    
            </init>
            <FeatureList>
                <Feature name="RID_RETRIEVE"/>
            </FeatureList>
        </Store>
        <Store name="PoolStore_2_2" type="SimpleFileStorage" desc="File Storage (Domain POOL)" pool="pool2">
            <init>BASE_DIR=target/docstore/test/pool2_2
                  checkIntervall=-1    
            </init>
            <FeatureList>
                <Feature name="RID_RETRIEVE"/>
            </FeatureList>
        </Store>
    </StoreDomain>
 </DocumentStoreCfg>
